"""Add user model

Revision ID: 35953e901f72
Revises: e237c14fa3a2
Create Date: 2023-08-10 20:35:53.768171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35953e901f72'
down_revision = 'e237c14fa3a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
