"""Fixed field create_date

Revision ID: b92b791450a0
Revises: 1ac121eeeb81
Create Date: 2023-08-14 16:35:21.317445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b92b791450a0'
down_revision = '1ac121eeeb81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
